# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Symengine Wiki
author: SymEngine Development Team
logo: logo.png

bibtex_bibfiles:
   - references.bib

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/Symengine/symengine.github.io # Online location of your book
  path_to_book: docs/wiki # Optional path to your book, relative to the repository root
  branch: src # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    [
      sphinx.ext.viewcode,
      sphinx.ext.intersphinx,
    ]
  config:
    intersphinx_mapping:
      sphinx-panels:
        - https://sphinx-panels.readthedocs.io/en/sphinx-book-theme/
        - null
      symengineAPI:
        - https://symengine.github.io/api-docs/
        - null
